title: Studious-Scrummers
description: "August 2023 to June 2024"
owner_name: The Studious Scrummers
github_username: henerystone123
github_repo: "Studious-Scrummers-Frontend"
baseurl: "/studious-scrummers"
remote_theme: jekyll/minima
minima:
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
